services:
  - type: web
    name: nba-backend
    env: python
    plan: free
    repo: https://github.com/Warsame-Egal/nba-live-tracker
    branch: main
    rootDir: nba-tracker-api
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: nba-frontend
    env: node
    plan: free
    repo: https://github.com/Warsame-Egal/nba-live-tracker
    branch: main
    rootDir: nba-tracker
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    envVars:
      - key: PORT
        value: 3000
      - key: VITE_API_BASE_URL
        value: https://REPLACE_ME.onrender.com
      - key: VITE_WS_URL
        value: wss://REPLACE_ME.onrender.com/api/v1/ws
