"""Remove GameStat relation from Player

Revision ID: 18987838d70d
Revises: a7ffe4e9fa7a
Create Date: 2025-07-17 01:14:23.411154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18987838d70d"
down_revision: Union[str, Sequence[str], None] = "a7ffe4e9fa7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
