"""Drop unused tables and models

Revision ID: 1b08548e9373
Revises: 629a7b9a837a
Create Date: 2025-07-17 00:12:44.300812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b08548e9373'
down_revision: Union[str, Sequence[str], None] = '629a7b9a837a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_game_player_stats')
    op.drop_table('player_search_results')
    op.drop_table('game_player_stats')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('game_stats')
    op.drop_table('games')
    op.drop_table('team_game_stats')
    op.drop_table('team_history_entries')
    op.drop_table('game_details')
    op.drop_table('team_awards_div')
    op.drop_table('box_score_player_stats')
    op.drop_table('box_score_team_stats')
    op.drop_table('game_leaders')
    op.drop_table('team_details')
    op.drop_table('team_records')
    op.drop_table('games_for_date')
    op.drop_table('player_summaries')
    op.drop_table('player_recent_games')
    op.drop_table('team_awards_championships')
    op.drop_table('team_roster_entries')
    op.drop_table('season_standings')
    op.drop_table('game_players')
    op.drop_table('team_search_results')
    op.drop_table('team_standings')
    op.drop_table('play_by_play_events')
    op.drop_table('team_awards_conf')
    op.drop_table('game_detail_players')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_detail_players',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_abbreviation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jersey_num', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('game_detail_players_pkey'))
    )
    op.create_table('team_awards_conf',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('team_awards_conf_pkey'))
    )
    op.create_table('play_by_play_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clock', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_tricode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score_home', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score_away', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('play_by_play_events_pkey'))
    )
    op.create_table('team_standings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('division', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('win_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('playoff_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('road_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conference_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('division_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('l10_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_streak', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_streak_str', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('games_back', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('team_standings_pkey'))
    )
    op.create_table('team_search_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('search_term', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('team_search_results_pkey'))
    )
    op.create_table('game_players',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_abbreviation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jersey_num', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('game_players_pkey'))
    )
    op.create_table('season_standings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('division', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('win_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('playoff_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('road_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conference_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('division_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('l10_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_streak', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_streak_str', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('games_back', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('season_standings_pkey'))
    )
    op.create_table('team_roster_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('jersey_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('height', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('school', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('team_roster_entries_pkey'))
    )
    op.create_table('team_awards_championships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('team_awards_championships_pkey'))
    )
    op.create_table('player_recent_games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PERSON_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('opponent_team_abbreviation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rebounds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('steals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('player_recent_games_pkey'))
    )
    op.create_table('player_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PERSON_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PLAYER_LAST_NAME', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('PLAYER_FIRST_NAME', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('PLAYER_SLUG', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('TEAM_ID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TEAM_SLUG', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('IS_DEFUNCT', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TEAM_CITY', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('TEAM_NAME', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('TEAM_ABBREVIATION', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('JERSEY_NUMBER', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('POSITION', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('HEIGHT', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('WEIGHT', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('COLLEGE', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('COUNTRY', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ROSTER_STATUS', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('PTS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('REB', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('AST', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('STATS_TIMEFRAME', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('FROM_YEAR', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TO_YEAR', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('player_summaries_pkey'))
    )
    op.create_table('games_for_date',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('matchup', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('game_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('arena', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_team_abbreviation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('home_team_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_team_abbreviation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('away_team_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('top_scorer_player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('top_scorer_player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('top_scorer_team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('top_scorer_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('top_scorer_rebounds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('top_scorer_assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('games_for_date_pkey'))
    )
    op.create_table('team_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('division', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('win_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('home_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('road_record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_10', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_streak', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('team_records_pkey'))
    )
    op.create_table('team_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('abbreviation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year_founded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('arena', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arena_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('general_manager', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('head_coach', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('division', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('team_details_pkey'))
    )
    op.create_table('game_leaders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('home_player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('home_player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_player_jerseyNum', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_player_position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_player_teamTricode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_player_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('home_player_rebounds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('home_player_assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('away_player_jerseyNum', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('away_player_position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('away_player_teamTricode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('away_player_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_player_rebounds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_player_assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('game_leaders_pkey'))
    )
    op.create_table('box_score_team_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_home_team', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_goal_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('three_point_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('free_throw_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rebounds_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('steals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('turnovers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('box_score_team_stats_pkey'))
    )
    op.create_table('box_score_player_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_home_team', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('minutes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rebounds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('steals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('turnovers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('box_score_player_stats_pkey'))
    )
    op.create_table('team_awards_div',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('team_awards_div_pkey'))
    )
    op.create_table('game_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('game_date_est', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('game_status_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visitor_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('game_details_pkey'))
    )
    op.create_table('team_history_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('team_history_entries_pkey'))
    )
    op.create_table('team_game_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_goal_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('three_point_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('free_throw_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rebounds_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('steals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('turnovers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('team_game_stats_pkey'))
    )
    op.create_table('game_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rebounds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('game_stats_game_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('game_stats_player_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('game_stats_pkey'))
    )
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('games_away_team_id_fkey')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('games_home_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('games_pkey'))
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('game_player_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_abbreviation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rebounds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('minutes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('steals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blocks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('turnovers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('game_player_stats_pkey'))
    )
    op.create_table('player_search_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('search_term', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('player_search_results_pkey'))
    )
    op.create_table('team_game_player_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('minutes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rebounds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('steals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('turnovers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('team_game_player_stats_pkey'))
    )
    # ### end Alembic commands ###
