"""add standings snapshot table

Revision ID: 2e2da960329e
Revises: ce96fd22032c
Create Date: 2025-07-16 21:14:16.500381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2da960329e'
down_revision: Union[str, Sequence[str], None] = 'ce96fd22032c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standings_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standings_snapshots_id'), 'standings_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_standings_snapshots_season'), 'standings_snapshots', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standings_snapshots_season'), table_name='standings_snapshots')
    op.drop_index(op.f('ix_standings_snapshots_id'), table_name='standings_snapshots')
    op.drop_table('standings_snapshots')
    # ### end Alembic commands ###
