"""refactor models

Revision ID: 5c350177dcdc
Revises: d3d4e1c8be9d
Create Date: 2025-07-17 21:15:10.470804

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c350177dcdc"
down_revision: Union[str, Sequence[str], None] = "d3d4e1c8be9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoreboard_games", "pbOdds_team")
    op.drop_column("scoreboard_games", "pbOdds_suspended")
    op.drop_column("scoreboard_games", "pbOdds_odds")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoreboard_games",
        sa.Column("pbOdds_odds", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column("scoreboard_games", sa.Column("pbOdds_suspended", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("scoreboard_games", sa.Column("pbOdds_team", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
