"""initial

Revision ID: 5ee887067160
Revises: 
Create Date: 2025-07-19 23:20:17.308671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ee887067160'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_leaders_cache',
    sa.Column('stat_category', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('stat_category', 'season')
    )
    op.drop_table('shot_chart_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shot_chart_cache',
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('player_id', 'season', name=op.f('shot_chart_cache_pkey'))
    )
    op.drop_table('league_leaders_cache')
    # ### end Alembic commands ###
