"""Add cache tables for schedule, players, teams

Revision ID: 629a7b9a837a
Revises: 83f2b5ac700f
Create Date: 2025-07-16 22:44:35.596173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629a7b9a837a'
down_revision: Union[str, Sequence[str], None] = '83f2b5ac700f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_score_cache',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('player_search_cache',
    sa.Column('search_term', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('search_term')
    )
    op.create_table('player_summary_cache',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('schedule_cache',
    sa.Column('game_date', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('game_date')
    )
    op.create_table('team_details_cache',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_details_cache')
    op.drop_table('schedule_cache')
    op.drop_table('player_summary_cache')
    op.drop_table('player_search_cache')
    op.drop_table('box_score_cache')
    # ### end Alembic commands ###
