"""reset migrations

Revision ID: 753f3a765394
Revises: 
Create Date: 2025-07-20 20:12:17.862481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '753f3a765394'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_leaders_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_leaders_cache',
    sa.Column('stat_category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('stat_category', 'season', name=op.f('league_leaders_cache_pkey'))
    )
    # ### end Alembic commands ###
