"""initial schema with new models

Revision ID: ce96fd22032c
Revises: 
Create Date: 2025-07-16 20:51:51.816427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce96fd22032c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_score_player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home_team', sa.Boolean(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('minutes', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('box_score_team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('is_home_team', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('field_goal_pct', sa.Float(), nullable=False),
    sa.Column('three_point_pct', sa.Float(), nullable=False),
    sa.Column('free_throw_pct', sa.Float(), nullable=False),
    sa.Column('rebounds_total', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_detail_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('jersey_num', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_date_est', sa.String(), nullable=False),
    sa.Column('game_status_text', sa.String(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('visitor_team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('home_player_id', sa.Integer(), nullable=True),
    sa.Column('home_player_name', sa.String(), nullable=True),
    sa.Column('home_player_jerseyNum', sa.String(), nullable=True),
    sa.Column('home_player_position', sa.String(), nullable=True),
    sa.Column('home_player_teamTricode', sa.String(), nullable=True),
    sa.Column('home_player_points', sa.Integer(), nullable=True),
    sa.Column('home_player_rebounds', sa.Integer(), nullable=True),
    sa.Column('home_player_assists', sa.Integer(), nullable=True),
    sa.Column('away_player_id', sa.Integer(), nullable=True),
    sa.Column('away_player_name', sa.String(), nullable=True),
    sa.Column('away_player_jerseyNum', sa.String(), nullable=True),
    sa.Column('away_player_position', sa.String(), nullable=True),
    sa.Column('away_player_teamTricode', sa.String(), nullable=True),
    sa.Column('away_player_points', sa.Integer(), nullable=True),
    sa.Column('away_player_rebounds', sa.Integer(), nullable=True),
    sa.Column('away_player_assists', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.String(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('jersey_num', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games_for_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('matchup', sa.String(), nullable=False),
    sa.Column('game_status', sa.String(), nullable=False),
    sa.Column('arena', sa.String(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('home_team_abbreviation', sa.String(), nullable=False),
    sa.Column('home_team_points', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_abbreviation', sa.String(), nullable=False),
    sa.Column('away_team_points', sa.Integer(), nullable=True),
    sa.Column('top_scorer_player_id', sa.Integer(), nullable=True),
    sa.Column('top_scorer_player_name', sa.String(), nullable=True),
    sa.Column('top_scorer_team_id', sa.Integer(), nullable=True),
    sa.Column('top_scorer_points', sa.Integer(), nullable=True),
    sa.Column('top_scorer_rebounds', sa.Integer(), nullable=True),
    sa.Column('top_scorer_assists', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('play_by_play_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('action_number', sa.Integer(), nullable=False),
    sa.Column('clock', sa.String(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_tricode', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('score_home', sa.String(), nullable=True),
    sa.Column('score_away', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_recent_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PERSON_ID', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('opponent_team_abbreviation', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_term', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PERSON_ID', sa.Integer(), nullable=False),
    sa.Column('PLAYER_LAST_NAME', sa.String(), nullable=False),
    sa.Column('PLAYER_FIRST_NAME', sa.String(), nullable=False),
    sa.Column('PLAYER_SLUG', sa.String(), nullable=True),
    sa.Column('TEAM_ID', sa.Integer(), nullable=True),
    sa.Column('TEAM_SLUG', sa.String(), nullable=True),
    sa.Column('IS_DEFUNCT', sa.Integer(), nullable=True),
    sa.Column('TEAM_CITY', sa.String(), nullable=True),
    sa.Column('TEAM_NAME', sa.String(), nullable=True),
    sa.Column('TEAM_ABBREVIATION', sa.String(), nullable=True),
    sa.Column('JERSEY_NUMBER', sa.String(), nullable=True),
    sa.Column('POSITION', sa.String(), nullable=True),
    sa.Column('HEIGHT', sa.String(), nullable=True),
    sa.Column('WEIGHT', sa.Integer(), nullable=True),
    sa.Column('COLLEGE', sa.String(), nullable=True),
    sa.Column('COUNTRY', sa.String(), nullable=True),
    sa.Column('ROSTER_STATUS', sa.String(), nullable=True),
    sa.Column('PTS', sa.Float(), nullable=True),
    sa.Column('REB', sa.Float(), nullable=True),
    sa.Column('AST', sa.Float(), nullable=True),
    sa.Column('STATS_TIMEFRAME', sa.String(), nullable=True),
    sa.Column('FROM_YEAR', sa.Integer(), nullable=True),
    sa.Column('TO_YEAR', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoreboard_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameDate', sa.String(), nullable=False),
    sa.Column('gameId', sa.String(), nullable=False),
    sa.Column('gameStatus', sa.Integer(), nullable=False),
    sa.Column('gameStatusText', sa.String(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('gameClock', sa.String(), nullable=True),
    sa.Column('gameTimeUTC', sa.String(), nullable=False),
    sa.Column('homeTeam_teamId', sa.Integer(), nullable=False),
    sa.Column('homeTeam_teamName', sa.String(), nullable=False),
    sa.Column('homeTeam_teamCity', sa.String(), nullable=False),
    sa.Column('homeTeam_teamTricode', sa.String(), nullable=False),
    sa.Column('homeTeam_wins', sa.Integer(), nullable=True),
    sa.Column('homeTeam_losses', sa.Integer(), nullable=True),
    sa.Column('homeTeam_score', sa.Integer(), nullable=True),
    sa.Column('homeTeam_timeoutsRemaining', sa.Integer(), nullable=True),
    sa.Column('awayTeam_teamId', sa.Integer(), nullable=False),
    sa.Column('awayTeam_teamName', sa.String(), nullable=False),
    sa.Column('awayTeam_teamCity', sa.String(), nullable=False),
    sa.Column('awayTeam_teamTricode', sa.String(), nullable=False),
    sa.Column('awayTeam_wins', sa.Integer(), nullable=True),
    sa.Column('awayTeam_losses', sa.Integer(), nullable=True),
    sa.Column('awayTeam_score', sa.Integer(), nullable=True),
    sa.Column('awayTeam_timeoutsRemaining', sa.Integer(), nullable=True),
    sa.Column('homeLeader_personId', sa.Integer(), nullable=True),
    sa.Column('homeLeader_name', sa.String(), nullable=True),
    sa.Column('homeLeader_jerseyNum', sa.String(), nullable=True),
    sa.Column('homeLeader_position', sa.String(), nullable=True),
    sa.Column('homeLeader_teamTricode', sa.String(), nullable=True),
    sa.Column('homeLeader_points', sa.Integer(), nullable=True),
    sa.Column('homeLeader_rebounds', sa.Integer(), nullable=True),
    sa.Column('homeLeader_assists', sa.Integer(), nullable=True),
    sa.Column('awayLeader_personId', sa.Integer(), nullable=True),
    sa.Column('awayLeader_name', sa.String(), nullable=True),
    sa.Column('awayLeader_jerseyNum', sa.String(), nullable=True),
    sa.Column('awayLeader_position', sa.String(), nullable=True),
    sa.Column('awayLeader_teamTricode', sa.String(), nullable=True),
    sa.Column('awayLeader_points', sa.Integer(), nullable=True),
    sa.Column('awayLeader_rebounds', sa.Integer(), nullable=True),
    sa.Column('awayLeader_assists', sa.Integer(), nullable=True),
    sa.Column('pbOdds_team', sa.String(), nullable=True),
    sa.Column('pbOdds_odds', sa.Float(), nullable=True),
    sa.Column('pbOdds_suspended', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoreboard_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoreboard_snapshots_game_date'), 'scoreboard_snapshots', ['game_date'], unique=False)
    op.create_index(op.f('ix_scoreboard_snapshots_id'), 'scoreboard_snapshots', ['id'], unique=False)
    op.create_table('season_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_city', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('conference', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_pct', sa.Float(), nullable=False),
    sa.Column('playoff_rank', sa.Integer(), nullable=False),
    sa.Column('home_record', sa.String(), nullable=False),
    sa.Column('road_record', sa.String(), nullable=False),
    sa.Column('conference_record', sa.String(), nullable=False),
    sa.Column('division_record', sa.String(), nullable=False),
    sa.Column('l10_record', sa.String(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('current_streak_str', sa.String(), nullable=False),
    sa.Column('games_back', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_awards_championships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_awards_conf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_awards_div',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('team_city', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('arena', sa.String(), nullable=True),
    sa.Column('arena_capacity', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('general_manager', sa.String(), nullable=True),
    sa.Column('head_coach', sa.String(), nullable=True),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_game_player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('minutes', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('field_goal_pct', sa.Float(), nullable=False),
    sa.Column('three_point_pct', sa.Float(), nullable=False),
    sa.Column('free_throw_pct', sa.Float(), nullable=False),
    sa.Column('rebounds_total', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_history_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('conference', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_pct', sa.Float(), nullable=False),
    sa.Column('home_record', sa.String(), nullable=False),
    sa.Column('road_record', sa.String(), nullable=False),
    sa.Column('last_10', sa.String(), nullable=False),
    sa.Column('current_streak', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_roster_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('jersey_number', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_term', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('team_city', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('conference', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_pct', sa.Float(), nullable=False),
    sa.Column('playoff_rank', sa.Integer(), nullable=False),
    sa.Column('home_record', sa.String(), nullable=False),
    sa.Column('road_record', sa.String(), nullable=False),
    sa.Column('conference_record', sa.String(), nullable=False),
    sa.Column('division_record', sa.String(), nullable=False),
    sa.Column('l10_record', sa.String(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('current_streak_str', sa.String(), nullable=False),
    sa.Column('games_back', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_abbreviation'), 'teams', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_stats')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_abbreviation'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('team_standings')
    op.drop_table('team_search_results')
    op.drop_table('team_roster_entries')
    op.drop_table('team_records')
    op.drop_table('team_history_entries')
    op.drop_table('team_game_stats')
    op.drop_table('team_game_player_stats')
    op.drop_table('team_details')
    op.drop_table('team_awards_div')
    op.drop_table('team_awards_conf')
    op.drop_table('team_awards_championships')
    op.drop_table('season_standings')
    op.drop_index(op.f('ix_scoreboard_snapshots_id'), table_name='scoreboard_snapshots')
    op.drop_index(op.f('ix_scoreboard_snapshots_game_date'), table_name='scoreboard_snapshots')
    op.drop_table('scoreboard_snapshots')
    op.drop_table('scoreboard_games')
    op.drop_table('player_summaries')
    op.drop_table('player_search_results')
    op.drop_table('player_recent_games')
    op.drop_table('play_by_play_events')
    op.drop_table('games_for_date')
    op.drop_table('game_players')
    op.drop_table('game_player_stats')
    op.drop_table('game_leaders')
    op.drop_table('game_details')
    op.drop_table('game_detail_players')
    op.drop_table('box_score_team_stats')
    op.drop_table('box_score_player_stats')
    # ### end Alembic commands ###
