"""remove game and gamestat

Revision ID: f373b23db9df
Revises: f4fa518d0669
Create Date: 2025-07-17 02:00:08.044421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f373b23db9df'
down_revision: Union[str, Sequence[str], None] = 'f4fa518d0669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('game_stats')
    op.drop_table('games')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rebounds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('game_stats_game_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('game_stats_player_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('game_stats_pkey'))
    )
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('games_away_team_id_fkey')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('games_home_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('games_pkey'))
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    # ### end Alembic commands ###
