name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend:
    name: Backend - FastAPI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files (Debugging Step)
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Backend Dependencies
        run: |
          cd nba-tracker-api
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Backend Code
        run: |
          cd nba-tracker-api
          source venv/bin/activate
          pip install flake8
          flake8 .

      - name: Run Backend Tests
        run: |
          cd nba-tracker-api  # <-- Updated path
          source venv/bin/activate
          pytest || echo "No tests found, skipping..."

  frontend:
    name: Frontend - React Build & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files (Debugging Step)
        run: ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        run: |
          cd nba-tracker
          npm install

      - name: Lint Frontend Code
        run: |
          cd nba-tracker
          npm run lint

      - name: Build Frontend
        run: |
          cd nba-tracker
          npm run build
