name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend:
    name: Backend - FastAPI Format, Lint, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          cd nba-tracker-api
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install black pytest

      - name: Format backend with Black
        run: |
          cd nba-tracker-api
          source venv/bin/activate
          black . --check

      - name: Run backend tests
        run: |
          cd nba-tracker-api
          source venv/bin/activate
          pytest || echo "No tests found, skipping..."

  frontend:
    name: Frontend - React Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          cd nba-tracker
          npm install

      - name: Lint frontend with ESLint
        run: |
          cd nba-tracker
          npm run lint

      - name: Format frontend with Prettier
        run: |
          cd nba-tracker
          npm run format

      - name: Build frontend with Vite
        run: |
          cd nba-tracker
          npm run build

  database:
    name: Database - Migrate, Populate, Export to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          cd nba-tracker-api
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Alembic migrations
        run: |
          cd nba-tracker-api
          source venv/bin/activate
          alembic upgrade head

      - name: Populate local DB with NBA data
        run: |
          cd nba-tracker-api
          source venv/bin/activate
          python populate_Database.py

      - name: Dump local DB to SQL
        run: |
          docker-compose up -d postgres
          sleep 10  # Wait for Postgres container to start
          docker exec -t nba-postgres pg_dump -U postgres nba > nba_dump.sql

      - name: Convert SQL to UTF-8
        shell: pwsh
        run: |
          Get-Content nba_dump.sql | Set-Content -Encoding UTF8 nba_dump_utf8.sql

      - name: Import SQL to Render Postgres
        run: |
          docker run -i --rm -v ${PWD}:/mnt postgres \
            psql -h ${{ secrets.RENDER_DB_HOST }} \
            -U ${{ secrets.RENDER_DB_USER }} \
            -d ${{ secrets.RENDER_DB_NAME }} \
            -f /mnt/nba_dump_utf8.sql
        env:
          PGPASSWORD: ${{ secrets.RENDER_DB_PASSWORD }}
