name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  RENDER_DB_USER: ${{ secrets.RENDER_DB_USER }}
  RENDER_DB_PASSWORD: ${{ secrets.RENDER_DB_PASSWORD }}
  RENDER_DB_NAME: ${{ secrets.RENDER_DB_NAME }}
  RENDER_DB_HOST: ${{ secrets.RENDER_DB_HOST }}

jobs:
  backend:
    name: Backend - FastAPI Format, Lint, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          cd nba-tracker-api
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install black pytest

      - name: Format backend with Black
        run: |
          cd nba-tracker-api
          source venv/bin/activate
          black . --check

      - name: Run backend tests
        run: |
          cd nba-tracker-api
          source venv/bin/activate
          pytest || echo "No tests found, skipping..."

  frontend:
    name: Frontend - React Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          cd nba-tracker
          npm install

      - name: Lint frontend with ESLint
        run: |
          cd nba-tracker
          npm run lint

      - name: Format frontend with Prettier
        run: |
          cd nba-tracker
          npm run format

      - name: Build frontend with Vite
        run: |
          cd nba-tracker
          npm run build

  database:
    name: Database - Migrate, Populate, Export to Render
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nba
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          cd nba-tracker-api
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Reset Alembic migration history and create new migration
        run: |
          cd nba-tracker-api
          source venv/bin/activate
          rm -rf alembic/versions/*
          export DATABASE_URL_SYNC="postgresql+psycopg2://postgres:postgres@localhost:5432/nba"
          alembic revision --autogenerate -m "Reset base migration"

      - name: Run Alembic migrations on local DB
        run: |
          cd nba-tracker-api
          source venv/bin/activate
          export DATABASE_URL_SYNC="postgresql+psycopg2://postgres:postgres@localhost:5432/nba"
          alembic upgrade head

      - name: Populate local DB with NBA data
        run: |
          cd nba-tracker-api
          source venv/bin/activate
          export DATABASE_URL="postgresql+asyncpg://postgres:postgres@localhost:5432/nba"
          python populate_Database.py

      - name: Dump local DB to SQL
        run: |
          docker run --rm -e PGPASSWORD=postgres \
            --network host \
            postgres pg_dump -h localhost -U postgres -d nba -F p > nba_dump.sql

      - name: Convert SQL to UTF-8
        shell: pwsh
        run: |
          Get-Content nba_dump.sql | Set-Content -Encoding UTF8 nba_dump_utf8.sql

      - name: Reset alembic_version table in Render DB
        run: |
          docker run -i --rm postgres psql \
            -h $RENDER_DB_HOST \
            -U $RENDER_DB_USER \
            -d $RENDER_DB_NAME \
            -c "DROP TABLE IF EXISTS alembic_version;"
        env:
          PGPASSWORD: ${{ secrets.RENDER_DB_PASSWORD }}

      - name: Import SQL to Render Postgres
        run: |
          docker run -i --rm -v ${PWD}:/mnt postgres \
            psql -h $RENDER_DB_HOST \
            -U $RENDER_DB_USER \
            -d $RENDER_DB_NAME \
            -f /mnt/nba_dump_utf8.sql
        env:
          PGPASSWORD: ${{ secrets.RENDER_DB_PASSWORD }}
